security:
    encoders:
        App\Infrastructure\Docrine\Entity\User:
            algorithm: argon2i
    providers:
        user_provider:
            id: App\Infrastructure\Security\Provider\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: user_provider
            pattern: ^/
            logout:
                path: app.logout
            guard:
                authenticators:
                    - App\Infrastructure\Security\Guard\WebAuthenticator
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
