version: '3'

services:
  blog-server:
    build: ./docker/php
    image: blog-symfony
    depends_on:
      - database
    volumes:
      - ./:/application:cached
      - /application/var/sessions/
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: db_clean_archi_docker_system
    ports:
      - 5434:5432
  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application:cached
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - blog-server